[package]
name = "thqm"
description = "Scripts over the network."
version = "0.1.3"
authors = ["Loic Coyle <loic.coyle@hotmail.fr>"]
edition = "2018"
readme = "README.md"
license = "MIT"
keywords = ["scripting", "http-server", "dynamic-menu"]
categories = ["command-line-utilities", "web-programming::http-server"]
repository = "https://github.com/loiccoyle/thqm.rs"

[[bin]]
name = "thqm"
path = "src/main.rs"

[features]
completions=["clap_complete"]

[dependencies]
clap = {version="3.0.14", features=["cargo"]}
clap_complete = {version="3.0.6", optional=true}
dirs = "4.0.0"
anyhow = "1.0.42"
log = "0.4.14"
env_logger = "0.9.0"
flate2 = "1.0.20"
tar = "0.4.35"
tera = "1"
qrcode = "0.12.0"
image = {version="0.23.0", features=["jpeg", "png"], default-features = false}
rouille = "3.2.1"
local-ip-address = "0.4.4"

[dev-dependencies]
ctor = "0.1.21"
