[package]
name = "thqm"
description = "A simple HTTP server to serve a dynamic menu for your scripts over the network."
version = "0.1.6"
authors = ["Loic Coyle <loic.coyle@hotmail.fr>"]
edition = "2021"
readme = "README.md"
license = "MIT"
keywords = ["scripting", "http-server", "dynamic-menu"]
categories = ["command-line-utilities", "web-programming::http-server"]
repository = "https://github.com/loiccoyle/thqm-rs"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
strip=true
codegen-units = 1
lto = true
panic = "abort"

[[bin]]
name = "thqm"
path = "src/main.rs"

[features]
completions=["clap_complete"]

[dependencies]
clap = {version="3.0.14", features= ["cargo"] }
clap_complete = {version="3.0.6", optional=true}
dirs = "4.0.0"
anyhow = "1.0.42"
log = "0.4.14"
env_logger = { default-features = false, version = "0.9.0" }
flate2 = "1.0.20"
tar = { default-features = false, version = "0.4.35" }
tera = { default-features = false, version = "1" }
qrcode = "0.12.0"
image = {version="0.23.0", features=["jpeg", "png"], default-features = false}
rouille = {version="3.2.1", default-features = false}
local-ip-address = "0.4.4"

[dev-dependencies]
ctor = "0.1.21"
assert_cmd = "2.0.4"
predicates = "2.1.1"
assert_fs = "1.0.7"
reqwest = { version = "0.11.9", features = ["blocking"] }
